// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package anomaly_detector

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.Configuration, b.ko.Spec.Configuration) {
		delta.Add("Spec.Configuration", a.ko.Spec.Configuration, b.ko.Spec.Configuration)
	} else if a.ko.Spec.Configuration != nil && b.ko.Spec.Configuration != nil {
		if len(a.ko.Spec.Configuration.ExcludedTimeRanges) != len(b.ko.Spec.Configuration.ExcludedTimeRanges) {
			delta.Add("Spec.Configuration.ExcludedTimeRanges", a.ko.Spec.Configuration.ExcludedTimeRanges, b.ko.Spec.Configuration.ExcludedTimeRanges)
		} else if len(a.ko.Spec.Configuration.ExcludedTimeRanges) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Configuration.ExcludedTimeRanges, b.ko.Spec.Configuration.ExcludedTimeRanges) {
				delta.Add("Spec.Configuration.ExcludedTimeRanges", a.ko.Spec.Configuration.ExcludedTimeRanges, b.ko.Spec.Configuration.ExcludedTimeRanges)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.Configuration.MetricTimezone, b.ko.Spec.Configuration.MetricTimezone) {
			delta.Add("Spec.Configuration.MetricTimezone", a.ko.Spec.Configuration.MetricTimezone, b.ko.Spec.Configuration.MetricTimezone)
		} else if a.ko.Spec.Configuration.MetricTimezone != nil && b.ko.Spec.Configuration.MetricTimezone != nil {
			if *a.ko.Spec.Configuration.MetricTimezone != *b.ko.Spec.Configuration.MetricTimezone {
				delta.Add("Spec.Configuration.MetricTimezone", a.ko.Spec.Configuration.MetricTimezone, b.ko.Spec.Configuration.MetricTimezone)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MetricCharacteristics, b.ko.Spec.MetricCharacteristics) {
		delta.Add("Spec.MetricCharacteristics", a.ko.Spec.MetricCharacteristics, b.ko.Spec.MetricCharacteristics)
	} else if a.ko.Spec.MetricCharacteristics != nil && b.ko.Spec.MetricCharacteristics != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.MetricCharacteristics.PeriodicSpikes, b.ko.Spec.MetricCharacteristics.PeriodicSpikes) {
			delta.Add("Spec.MetricCharacteristics.PeriodicSpikes", a.ko.Spec.MetricCharacteristics.PeriodicSpikes, b.ko.Spec.MetricCharacteristics.PeriodicSpikes)
		} else if a.ko.Spec.MetricCharacteristics.PeriodicSpikes != nil && b.ko.Spec.MetricCharacteristics.PeriodicSpikes != nil {
			if *a.ko.Spec.MetricCharacteristics.PeriodicSpikes != *b.ko.Spec.MetricCharacteristics.PeriodicSpikes {
				delta.Add("Spec.MetricCharacteristics.PeriodicSpikes", a.ko.Spec.MetricCharacteristics.PeriodicSpikes, b.ko.Spec.MetricCharacteristics.PeriodicSpikes)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MetricMathAnomalyDetector, b.ko.Spec.MetricMathAnomalyDetector) {
		delta.Add("Spec.MetricMathAnomalyDetector", a.ko.Spec.MetricMathAnomalyDetector, b.ko.Spec.MetricMathAnomalyDetector)
	} else if a.ko.Spec.MetricMathAnomalyDetector != nil && b.ko.Spec.MetricMathAnomalyDetector != nil {
		if len(a.ko.Spec.MetricMathAnomalyDetector.MetricDataQueries) != len(b.ko.Spec.MetricMathAnomalyDetector.MetricDataQueries) {
			delta.Add("Spec.MetricMathAnomalyDetector.MetricDataQueries", a.ko.Spec.MetricMathAnomalyDetector.MetricDataQueries, b.ko.Spec.MetricMathAnomalyDetector.MetricDataQueries)
		} else if len(a.ko.Spec.MetricMathAnomalyDetector.MetricDataQueries) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.MetricMathAnomalyDetector.MetricDataQueries, b.ko.Spec.MetricMathAnomalyDetector.MetricDataQueries) {
				delta.Add("Spec.MetricMathAnomalyDetector.MetricDataQueries", a.ko.Spec.MetricMathAnomalyDetector.MetricDataQueries, b.ko.Spec.MetricMathAnomalyDetector.MetricDataQueries)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.SingleMetricAnomalyDetector, b.ko.Spec.SingleMetricAnomalyDetector) {
		delta.Add("Spec.SingleMetricAnomalyDetector", a.ko.Spec.SingleMetricAnomalyDetector, b.ko.Spec.SingleMetricAnomalyDetector)
	} else if a.ko.Spec.SingleMetricAnomalyDetector != nil && b.ko.Spec.SingleMetricAnomalyDetector != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.SingleMetricAnomalyDetector.AccountID, b.ko.Spec.SingleMetricAnomalyDetector.AccountID) {
			delta.Add("Spec.SingleMetricAnomalyDetector.AccountID", a.ko.Spec.SingleMetricAnomalyDetector.AccountID, b.ko.Spec.SingleMetricAnomalyDetector.AccountID)
		} else if a.ko.Spec.SingleMetricAnomalyDetector.AccountID != nil && b.ko.Spec.SingleMetricAnomalyDetector.AccountID != nil {
			if *a.ko.Spec.SingleMetricAnomalyDetector.AccountID != *b.ko.Spec.SingleMetricAnomalyDetector.AccountID {
				delta.Add("Spec.SingleMetricAnomalyDetector.AccountID", a.ko.Spec.SingleMetricAnomalyDetector.AccountID, b.ko.Spec.SingleMetricAnomalyDetector.AccountID)
			}
		}
		if len(a.ko.Spec.SingleMetricAnomalyDetector.Dimensions) != len(b.ko.Spec.SingleMetricAnomalyDetector.Dimensions) {
			delta.Add("Spec.SingleMetricAnomalyDetector.Dimensions", a.ko.Spec.SingleMetricAnomalyDetector.Dimensions, b.ko.Spec.SingleMetricAnomalyDetector.Dimensions)
		} else if len(a.ko.Spec.SingleMetricAnomalyDetector.Dimensions) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.SingleMetricAnomalyDetector.Dimensions, b.ko.Spec.SingleMetricAnomalyDetector.Dimensions) {
				delta.Add("Spec.SingleMetricAnomalyDetector.Dimensions", a.ko.Spec.SingleMetricAnomalyDetector.Dimensions, b.ko.Spec.SingleMetricAnomalyDetector.Dimensions)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.SingleMetricAnomalyDetector.MetricName, b.ko.Spec.SingleMetricAnomalyDetector.MetricName) {
			delta.Add("Spec.SingleMetricAnomalyDetector.MetricName", a.ko.Spec.SingleMetricAnomalyDetector.MetricName, b.ko.Spec.SingleMetricAnomalyDetector.MetricName)
		} else if a.ko.Spec.SingleMetricAnomalyDetector.MetricName != nil && b.ko.Spec.SingleMetricAnomalyDetector.MetricName != nil {
			if *a.ko.Spec.SingleMetricAnomalyDetector.MetricName != *b.ko.Spec.SingleMetricAnomalyDetector.MetricName {
				delta.Add("Spec.SingleMetricAnomalyDetector.MetricName", a.ko.Spec.SingleMetricAnomalyDetector.MetricName, b.ko.Spec.SingleMetricAnomalyDetector.MetricName)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.SingleMetricAnomalyDetector.Namespace, b.ko.Spec.SingleMetricAnomalyDetector.Namespace) {
			delta.Add("Spec.SingleMetricAnomalyDetector.Namespace", a.ko.Spec.SingleMetricAnomalyDetector.Namespace, b.ko.Spec.SingleMetricAnomalyDetector.Namespace)
		} else if a.ko.Spec.SingleMetricAnomalyDetector.Namespace != nil && b.ko.Spec.SingleMetricAnomalyDetector.Namespace != nil {
			if *a.ko.Spec.SingleMetricAnomalyDetector.Namespace != *b.ko.Spec.SingleMetricAnomalyDetector.Namespace {
				delta.Add("Spec.SingleMetricAnomalyDetector.Namespace", a.ko.Spec.SingleMetricAnomalyDetector.Namespace, b.ko.Spec.SingleMetricAnomalyDetector.Namespace)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.SingleMetricAnomalyDetector.Stat, b.ko.Spec.SingleMetricAnomalyDetector.Stat) {
			delta.Add("Spec.SingleMetricAnomalyDetector.Stat", a.ko.Spec.SingleMetricAnomalyDetector.Stat, b.ko.Spec.SingleMetricAnomalyDetector.Stat)
		} else if a.ko.Spec.SingleMetricAnomalyDetector.Stat != nil && b.ko.Spec.SingleMetricAnomalyDetector.Stat != nil {
			if *a.ko.Spec.SingleMetricAnomalyDetector.Stat != *b.ko.Spec.SingleMetricAnomalyDetector.Stat {
				delta.Add("Spec.SingleMetricAnomalyDetector.Stat", a.ko.Spec.SingleMetricAnomalyDetector.Stat, b.ko.Spec.SingleMetricAnomalyDetector.Stat)
			}
		}
	}

	return delta
}
