// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package anomaly_detector

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/cloudwatch"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/cloudwatch/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/cloudwatch-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.AnomalyDetector{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}
	if r.ko.Status.AnomalyDetectorID == nil || *r.ko.Status.AnomalyDetectorID == "" {
		return nil, ackerr.NotFound
	}
	input.AnomalyDetectorIds = []string{*r.ko.Status.AnomalyDetectorID}

	var resp *svcsdk.DescribeAnomalyDetectorsOutput
	resp, err = rm.sdkapi.DescribeAnomalyDetectors(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeAnomalyDetectors", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "UNKNOWN" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.AnomalyDetectors {
		if elem.AnomalyDetectorId != nil {
			ko.Status.AnomalyDetectorID = elem.AnomalyDetectorId
		} else {
			ko.Status.AnomalyDetectorID = nil
		}
		if elem.Configuration != nil {
			f1 := &svcapitypes.AnomalyDetectorConfiguration{}
			if elem.Configuration.ExcludedTimeRanges != nil {
				f1f0 := []*svcapitypes.Range{}
				for _, f1f0iter := range elem.Configuration.ExcludedTimeRanges {
					f1f0elem := &svcapitypes.Range{}
					if f1f0iter.EndTime != nil {
						f1f0elem.EndTime = &metav1.Time{*f1f0iter.EndTime}
					}
					if f1f0iter.StartTime != nil {
						f1f0elem.StartTime = &metav1.Time{*f1f0iter.StartTime}
					}
					f1f0 = append(f1f0, f1f0elem)
				}
				f1.ExcludedTimeRanges = f1f0
			}
			if elem.Configuration.MetricTimezone != nil {
				f1.MetricTimezone = elem.Configuration.MetricTimezone
			}
			ko.Spec.Configuration = f1
		} else {
			ko.Spec.Configuration = nil
		}
		if elem.MetricCharacteristics != nil {
			f2 := &svcapitypes.MetricCharacteristics{}
			if elem.MetricCharacteristics.PeriodicSpikes != nil {
				f2.PeriodicSpikes = elem.MetricCharacteristics.PeriodicSpikes
			}
			ko.Spec.MetricCharacteristics = f2
		} else {
			ko.Spec.MetricCharacteristics = nil
		}
		if elem.MetricMathAnomalyDetector != nil {
			f3 := &svcapitypes.MetricMathAnomalyDetector{}
			if elem.MetricMathAnomalyDetector.MetricDataQueries != nil {
				f3f0 := []*svcapitypes.MetricDataQuery{}
				for _, f3f0iter := range elem.MetricMathAnomalyDetector.MetricDataQueries {
					f3f0elem := &svcapitypes.MetricDataQuery{}
					if f3f0iter.AccountId != nil {
						f3f0elem.AccountID = f3f0iter.AccountId
					}
					if f3f0iter.Expression != nil {
						f3f0elem.Expression = f3f0iter.Expression
					}
					if f3f0iter.Id != nil {
						f3f0elem.ID = f3f0iter.Id
					}
					if f3f0iter.Label != nil {
						f3f0elem.Label = f3f0iter.Label
					}
					if f3f0iter.MetricStat != nil {
						f3f0elemf4 := &svcapitypes.MetricStat{}
						if f3f0iter.MetricStat.Metric != nil {
							f3f0elemf4f0 := &svcapitypes.Metric{}
							if f3f0iter.MetricStat.Metric.Dimensions != nil {
								f3f0elemf4f0f0 := []*svcapitypes.Dimension{}
								for _, f3f0elemf4f0f0iter := range f3f0iter.MetricStat.Metric.Dimensions {
									f3f0elemf4f0f0elem := &svcapitypes.Dimension{}
									if f3f0elemf4f0f0iter.Name != nil {
										f3f0elemf4f0f0elem.Name = f3f0elemf4f0f0iter.Name
									}
									if f3f0elemf4f0f0iter.Value != nil {
										f3f0elemf4f0f0elem.Value = f3f0elemf4f0f0iter.Value
									}
									f3f0elemf4f0f0 = append(f3f0elemf4f0f0, f3f0elemf4f0f0elem)
								}
								f3f0elemf4f0.Dimensions = f3f0elemf4f0f0
							}
							if f3f0iter.MetricStat.Metric.MetricName != nil {
								f3f0elemf4f0.MetricName = f3f0iter.MetricStat.Metric.MetricName
							}
							if f3f0iter.MetricStat.Metric.Namespace != nil {
								f3f0elemf4f0.Namespace = f3f0iter.MetricStat.Metric.Namespace
							}
							f3f0elemf4.Metric = f3f0elemf4f0
						}
						if f3f0iter.MetricStat.Period != nil {
							periodCopy := int64(*f3f0iter.MetricStat.Period)
							f3f0elemf4.Period = &periodCopy
						}
						if f3f0iter.MetricStat.Stat != nil {
							f3f0elemf4.Stat = f3f0iter.MetricStat.Stat
						}
						if f3f0iter.MetricStat.Unit != "" {
							f3f0elemf4.Unit = aws.String(string(f3f0iter.MetricStat.Unit))
						}
						f3f0elem.MetricStat = f3f0elemf4
					}
					if f3f0iter.Period != nil {
						periodCopy := int64(*f3f0iter.Period)
						f3f0elem.Period = &periodCopy
					}
					if f3f0iter.ReturnData != nil {
						f3f0elem.ReturnData = f3f0iter.ReturnData
					}
					f3f0 = append(f3f0, f3f0elem)
				}
				f3.MetricDataQueries = f3f0
			}
			ko.Spec.MetricMathAnomalyDetector = f3
		} else {
			ko.Spec.MetricMathAnomalyDetector = nil
		}
		if elem.SingleMetricAnomalyDetector != nil {
			f4 := &svcapitypes.SingleMetricAnomalyDetector{}
			if elem.SingleMetricAnomalyDetector.AccountId != nil {
				f4.AccountID = elem.SingleMetricAnomalyDetector.AccountId
			}
			if elem.SingleMetricAnomalyDetector.Dimensions != nil {
				f4f1 := []*svcapitypes.Dimension{}
				for _, f4f1iter := range elem.SingleMetricAnomalyDetector.Dimensions {
					f4f1elem := &svcapitypes.Dimension{}
					if f4f1iter.Name != nil {
						f4f1elem.Name = f4f1iter.Name
					}
					if f4f1iter.Value != nil {
						f4f1elem.Value = f4f1iter.Value
					}
					f4f1 = append(f4f1, f4f1elem)
				}
				f4.Dimensions = f4f1
			}
			if elem.SingleMetricAnomalyDetector.MetricName != nil {
				f4.MetricName = elem.SingleMetricAnomalyDetector.MetricName
			}
			if elem.SingleMetricAnomalyDetector.Namespace != nil {
				f4.Namespace = elem.SingleMetricAnomalyDetector.Namespace
			}
			if elem.SingleMetricAnomalyDetector.Stat != nil {
				f4.Stat = elem.SingleMetricAnomalyDetector.Stat
			}
			ko.Spec.SingleMetricAnomalyDetector = f4
		} else {
			ko.Spec.SingleMetricAnomalyDetector = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	return r.ko.Status.AnomalyDetectorID == nil

}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeAnomalyDetectorsInput, error) {
	res := &svcsdk.DescribeAnomalyDetectorsInput{}

	if r.ko.Status.AnomalyDetectorID != nil {
		f0 := []string{}
		f0 = append(f0, *r.ko.Status.AnomalyDetectorID)
		res.AnomalyDetectorIds = f0
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.PutAnomalyDetectorOutput
	_ = resp
	resp, err = rm.sdkapi.PutAnomalyDetector(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "PutAnomalyDetector", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.AnomalyDetectorId != nil {
		ko.Status.AnomalyDetectorID = resp.AnomalyDetectorId
	} else {
		ko.Status.AnomalyDetectorID = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.PutAnomalyDetectorInput, error) {
	res := &svcsdk.PutAnomalyDetectorInput{}

	if r.ko.Spec.Configuration != nil {
		f0 := &svcsdktypes.AnomalyDetectorConfiguration{}
		if r.ko.Spec.Configuration.ExcludedTimeRanges != nil {
			f0f0 := []svcsdktypes.Range{}
			for _, f0f0iter := range r.ko.Spec.Configuration.ExcludedTimeRanges {
				f0f0elem := &svcsdktypes.Range{}
				if f0f0iter.EndTime != nil {
					f0f0elem.EndTime = &f0f0iter.EndTime.Time
				}
				if f0f0iter.StartTime != nil {
					f0f0elem.StartTime = &f0f0iter.StartTime.Time
				}
				f0f0 = append(f0f0, *f0f0elem)
			}
			f0.ExcludedTimeRanges = f0f0
		}
		if r.ko.Spec.Configuration.MetricTimezone != nil {
			f0.MetricTimezone = r.ko.Spec.Configuration.MetricTimezone
		}
		res.Configuration = f0
	}
	if r.ko.Spec.MetricCharacteristics != nil {
		f1 := &svcsdktypes.MetricCharacteristics{}
		if r.ko.Spec.MetricCharacteristics.PeriodicSpikes != nil {
			f1.PeriodicSpikes = r.ko.Spec.MetricCharacteristics.PeriodicSpikes
		}
		res.MetricCharacteristics = f1
	}
	if r.ko.Spec.MetricMathAnomalyDetector != nil {
		f2 := &svcsdktypes.MetricMathAnomalyDetector{}
		if r.ko.Spec.MetricMathAnomalyDetector.MetricDataQueries != nil {
			f2f0 := []svcsdktypes.MetricDataQuery{}
			for _, f2f0iter := range r.ko.Spec.MetricMathAnomalyDetector.MetricDataQueries {
				f2f0elem := &svcsdktypes.MetricDataQuery{}
				if f2f0iter.AccountID != nil {
					f2f0elem.AccountId = f2f0iter.AccountID
				}
				if f2f0iter.Expression != nil {
					f2f0elem.Expression = f2f0iter.Expression
				}
				if f2f0iter.ID != nil {
					f2f0elem.Id = f2f0iter.ID
				}
				if f2f0iter.Label != nil {
					f2f0elem.Label = f2f0iter.Label
				}
				if f2f0iter.MetricStat != nil {
					f2f0elemf4 := &svcsdktypes.MetricStat{}
					if f2f0iter.MetricStat.Metric != nil {
						f2f0elemf4f0 := &svcsdktypes.Metric{}
						if f2f0iter.MetricStat.Metric.Dimensions != nil {
							f2f0elemf4f0f0 := []svcsdktypes.Dimension{}
							for _, f2f0elemf4f0f0iter := range f2f0iter.MetricStat.Metric.Dimensions {
								f2f0elemf4f0f0elem := &svcsdktypes.Dimension{}
								if f2f0elemf4f0f0iter.Name != nil {
									f2f0elemf4f0f0elem.Name = f2f0elemf4f0f0iter.Name
								}
								if f2f0elemf4f0f0iter.Value != nil {
									f2f0elemf4f0f0elem.Value = f2f0elemf4f0f0iter.Value
								}
								f2f0elemf4f0f0 = append(f2f0elemf4f0f0, *f2f0elemf4f0f0elem)
							}
							f2f0elemf4f0.Dimensions = f2f0elemf4f0f0
						}
						if f2f0iter.MetricStat.Metric.MetricName != nil {
							f2f0elemf4f0.MetricName = f2f0iter.MetricStat.Metric.MetricName
						}
						if f2f0iter.MetricStat.Metric.Namespace != nil {
							f2f0elemf4f0.Namespace = f2f0iter.MetricStat.Metric.Namespace
						}
						f2f0elemf4.Metric = f2f0elemf4f0
					}
					if f2f0iter.MetricStat.Period != nil {
						periodCopy0 := *f2f0iter.MetricStat.Period
						if periodCopy0 > math.MaxInt32 || periodCopy0 < math.MinInt32 {
							return nil, fmt.Errorf("error: field Period is of type int32")
						}
						periodCopy := int32(periodCopy0)
						f2f0elemf4.Period = &periodCopy
					}
					if f2f0iter.MetricStat.Stat != nil {
						f2f0elemf4.Stat = f2f0iter.MetricStat.Stat
					}
					if f2f0iter.MetricStat.Unit != nil {
						f2f0elemf4.Unit = svcsdktypes.StandardUnit(*f2f0iter.MetricStat.Unit)
					}
					f2f0elem.MetricStat = f2f0elemf4
				}
				if f2f0iter.Period != nil {
					periodCopy0 := *f2f0iter.Period
					if periodCopy0 > math.MaxInt32 || periodCopy0 < math.MinInt32 {
						return nil, fmt.Errorf("error: field Period is of type int32")
					}
					periodCopy := int32(periodCopy0)
					f2f0elem.Period = &periodCopy
				}
				if f2f0iter.ReturnData != nil {
					f2f0elem.ReturnData = f2f0iter.ReturnData
				}
				f2f0 = append(f2f0, *f2f0elem)
			}
			f2.MetricDataQueries = f2f0
		}
		res.MetricMathAnomalyDetector = f2
	}
	if r.ko.Spec.SingleMetricAnomalyDetector != nil {
		f3 := &svcsdktypes.SingleMetricAnomalyDetector{}
		if r.ko.Spec.SingleMetricAnomalyDetector.AccountID != nil {
			f3.AccountId = r.ko.Spec.SingleMetricAnomalyDetector.AccountID
		}
		if r.ko.Spec.SingleMetricAnomalyDetector.Dimensions != nil {
			f3f1 := []svcsdktypes.Dimension{}
			for _, f3f1iter := range r.ko.Spec.SingleMetricAnomalyDetector.Dimensions {
				f3f1elem := &svcsdktypes.Dimension{}
				if f3f1iter.Name != nil {
					f3f1elem.Name = f3f1iter.Name
				}
				if f3f1iter.Value != nil {
					f3f1elem.Value = f3f1iter.Value
				}
				f3f1 = append(f3f1, *f3f1elem)
			}
			f3.Dimensions = f3f1
		}
		if r.ko.Spec.SingleMetricAnomalyDetector.MetricName != nil {
			f3.MetricName = r.ko.Spec.SingleMetricAnomalyDetector.MetricName
		}
		if r.ko.Spec.SingleMetricAnomalyDetector.Namespace != nil {
			f3.Namespace = r.ko.Spec.SingleMetricAnomalyDetector.Namespace
		}
		if r.ko.Spec.SingleMetricAnomalyDetector.Stat != nil {
			f3.Stat = r.ko.Spec.SingleMetricAnomalyDetector.Stat
		}
		res.SingleMetricAnomalyDetector = f3
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.PutAnomalyDetectorOutput
	_ = resp
	resp, err = rm.sdkapi.PutAnomalyDetector(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "PutAnomalyDetector", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.AnomalyDetectorId != nil {
		ko.Status.AnomalyDetectorID = resp.AnomalyDetectorId
	} else {
		ko.Status.AnomalyDetectorID = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.PutAnomalyDetectorInput, error) {
	res := &svcsdk.PutAnomalyDetectorInput{}

	if r.ko.Spec.Configuration != nil {
		f0 := &svcsdktypes.AnomalyDetectorConfiguration{}
		if r.ko.Spec.Configuration.ExcludedTimeRanges != nil {
			f0f0 := []svcsdktypes.Range{}
			for _, f0f0iter := range r.ko.Spec.Configuration.ExcludedTimeRanges {
				f0f0elem := &svcsdktypes.Range{}
				if f0f0iter.EndTime != nil {
					f0f0elem.EndTime = &f0f0iter.EndTime.Time
				}
				if f0f0iter.StartTime != nil {
					f0f0elem.StartTime = &f0f0iter.StartTime.Time
				}
				f0f0 = append(f0f0, *f0f0elem)
			}
			f0.ExcludedTimeRanges = f0f0
		}
		if r.ko.Spec.Configuration.MetricTimezone != nil {
			f0.MetricTimezone = r.ko.Spec.Configuration.MetricTimezone
		}
		res.Configuration = f0
	}
	if r.ko.Spec.MetricCharacteristics != nil {
		f1 := &svcsdktypes.MetricCharacteristics{}
		if r.ko.Spec.MetricCharacteristics.PeriodicSpikes != nil {
			f1.PeriodicSpikes = r.ko.Spec.MetricCharacteristics.PeriodicSpikes
		}
		res.MetricCharacteristics = f1
	}
	if r.ko.Spec.MetricMathAnomalyDetector != nil {
		f2 := &svcsdktypes.MetricMathAnomalyDetector{}
		if r.ko.Spec.MetricMathAnomalyDetector.MetricDataQueries != nil {
			f2f0 := []svcsdktypes.MetricDataQuery{}
			for _, f2f0iter := range r.ko.Spec.MetricMathAnomalyDetector.MetricDataQueries {
				f2f0elem := &svcsdktypes.MetricDataQuery{}
				if f2f0iter.AccountID != nil {
					f2f0elem.AccountId = f2f0iter.AccountID
				}
				if f2f0iter.Expression != nil {
					f2f0elem.Expression = f2f0iter.Expression
				}
				if f2f0iter.ID != nil {
					f2f0elem.Id = f2f0iter.ID
				}
				if f2f0iter.Label != nil {
					f2f0elem.Label = f2f0iter.Label
				}
				if f2f0iter.MetricStat != nil {
					f2f0elemf4 := &svcsdktypes.MetricStat{}
					if f2f0iter.MetricStat.Metric != nil {
						f2f0elemf4f0 := &svcsdktypes.Metric{}
						if f2f0iter.MetricStat.Metric.Dimensions != nil {
							f2f0elemf4f0f0 := []svcsdktypes.Dimension{}
							for _, f2f0elemf4f0f0iter := range f2f0iter.MetricStat.Metric.Dimensions {
								f2f0elemf4f0f0elem := &svcsdktypes.Dimension{}
								if f2f0elemf4f0f0iter.Name != nil {
									f2f0elemf4f0f0elem.Name = f2f0elemf4f0f0iter.Name
								}
								if f2f0elemf4f0f0iter.Value != nil {
									f2f0elemf4f0f0elem.Value = f2f0elemf4f0f0iter.Value
								}
								f2f0elemf4f0f0 = append(f2f0elemf4f0f0, *f2f0elemf4f0f0elem)
							}
							f2f0elemf4f0.Dimensions = f2f0elemf4f0f0
						}
						if f2f0iter.MetricStat.Metric.MetricName != nil {
							f2f0elemf4f0.MetricName = f2f0iter.MetricStat.Metric.MetricName
						}
						if f2f0iter.MetricStat.Metric.Namespace != nil {
							f2f0elemf4f0.Namespace = f2f0iter.MetricStat.Metric.Namespace
						}
						f2f0elemf4.Metric = f2f0elemf4f0
					}
					if f2f0iter.MetricStat.Period != nil {
						periodCopy0 := *f2f0iter.MetricStat.Period
						if periodCopy0 > math.MaxInt32 || periodCopy0 < math.MinInt32 {
							return nil, fmt.Errorf("error: field Period is of type int32")
						}
						periodCopy := int32(periodCopy0)
						f2f0elemf4.Period = &periodCopy
					}
					if f2f0iter.MetricStat.Stat != nil {
						f2f0elemf4.Stat = f2f0iter.MetricStat.Stat
					}
					if f2f0iter.MetricStat.Unit != nil {
						f2f0elemf4.Unit = svcsdktypes.StandardUnit(*f2f0iter.MetricStat.Unit)
					}
					f2f0elem.MetricStat = f2f0elemf4
				}
				if f2f0iter.Period != nil {
					periodCopy0 := *f2f0iter.Period
					if periodCopy0 > math.MaxInt32 || periodCopy0 < math.MinInt32 {
						return nil, fmt.Errorf("error: field Period is of type int32")
					}
					periodCopy := int32(periodCopy0)
					f2f0elem.Period = &periodCopy
				}
				if f2f0iter.ReturnData != nil {
					f2f0elem.ReturnData = f2f0iter.ReturnData
				}
				f2f0 = append(f2f0, *f2f0elem)
			}
			f2.MetricDataQueries = f2f0
		}
		res.MetricMathAnomalyDetector = f2
	}
	if r.ko.Spec.SingleMetricAnomalyDetector != nil {
		f3 := &svcsdktypes.SingleMetricAnomalyDetector{}
		if r.ko.Spec.SingleMetricAnomalyDetector.AccountID != nil {
			f3.AccountId = r.ko.Spec.SingleMetricAnomalyDetector.AccountID
		}
		if r.ko.Spec.SingleMetricAnomalyDetector.Dimensions != nil {
			f3f1 := []svcsdktypes.Dimension{}
			for _, f3f1iter := range r.ko.Spec.SingleMetricAnomalyDetector.Dimensions {
				f3f1elem := &svcsdktypes.Dimension{}
				if f3f1iter.Name != nil {
					f3f1elem.Name = f3f1iter.Name
				}
				if f3f1iter.Value != nil {
					f3f1elem.Value = f3f1iter.Value
				}
				f3f1 = append(f3f1, *f3f1elem)
			}
			f3.Dimensions = f3f1
		}
		if r.ko.Spec.SingleMetricAnomalyDetector.MetricName != nil {
			f3.MetricName = r.ko.Spec.SingleMetricAnomalyDetector.MetricName
		}
		if r.ko.Spec.SingleMetricAnomalyDetector.Namespace != nil {
			f3.Namespace = r.ko.Spec.SingleMetricAnomalyDetector.Namespace
		}
		if r.ko.Spec.SingleMetricAnomalyDetector.Stat != nil {
			f3.Stat = r.ko.Spec.SingleMetricAnomalyDetector.Stat
		}
		res.SingleMetricAnomalyDetector = f3
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	if r.ko.Status.AnomalyDetectorID != nil {
		input.AnomalyDetectorId = r.ko.Status.AnomalyDetectorID
	}

	var resp *svcsdk.DeleteAnomalyDetectorOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteAnomalyDetector(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteAnomalyDetector", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteAnomalyDetectorInput, error) {
	res := &svcsdk.DeleteAnomalyDetectorInput{}

	if r.ko.Status.AnomalyDetectorID != nil {
		res.AnomalyDetectorId = r.ko.Status.AnomalyDetectorID
	}
	if r.ko.Spec.MetricMathAnomalyDetector != nil {
		f1 := &svcsdktypes.MetricMathAnomalyDetector{}
		if r.ko.Spec.MetricMathAnomalyDetector.MetricDataQueries != nil {
			f1f0 := []svcsdktypes.MetricDataQuery{}
			for _, f1f0iter := range r.ko.Spec.MetricMathAnomalyDetector.MetricDataQueries {
				f1f0elem := &svcsdktypes.MetricDataQuery{}
				if f1f0iter.AccountID != nil {
					f1f0elem.AccountId = f1f0iter.AccountID
				}
				if f1f0iter.Expression != nil {
					f1f0elem.Expression = f1f0iter.Expression
				}
				if f1f0iter.ID != nil {
					f1f0elem.Id = f1f0iter.ID
				}
				if f1f0iter.Label != nil {
					f1f0elem.Label = f1f0iter.Label
				}
				if f1f0iter.MetricStat != nil {
					f1f0elemf4 := &svcsdktypes.MetricStat{}
					if f1f0iter.MetricStat.Metric != nil {
						f1f0elemf4f0 := &svcsdktypes.Metric{}
						if f1f0iter.MetricStat.Metric.Dimensions != nil {
							f1f0elemf4f0f0 := []svcsdktypes.Dimension{}
							for _, f1f0elemf4f0f0iter := range f1f0iter.MetricStat.Metric.Dimensions {
								f1f0elemf4f0f0elem := &svcsdktypes.Dimension{}
								if f1f0elemf4f0f0iter.Name != nil {
									f1f0elemf4f0f0elem.Name = f1f0elemf4f0f0iter.Name
								}
								if f1f0elemf4f0f0iter.Value != nil {
									f1f0elemf4f0f0elem.Value = f1f0elemf4f0f0iter.Value
								}
								f1f0elemf4f0f0 = append(f1f0elemf4f0f0, *f1f0elemf4f0f0elem)
							}
							f1f0elemf4f0.Dimensions = f1f0elemf4f0f0
						}
						if f1f0iter.MetricStat.Metric.MetricName != nil {
							f1f0elemf4f0.MetricName = f1f0iter.MetricStat.Metric.MetricName
						}
						if f1f0iter.MetricStat.Metric.Namespace != nil {
							f1f0elemf4f0.Namespace = f1f0iter.MetricStat.Metric.Namespace
						}
						f1f0elemf4.Metric = f1f0elemf4f0
					}
					if f1f0iter.MetricStat.Period != nil {
						periodCopy0 := *f1f0iter.MetricStat.Period
						if periodCopy0 > math.MaxInt32 || periodCopy0 < math.MinInt32 {
							return nil, fmt.Errorf("error: field Period is of type int32")
						}
						periodCopy := int32(periodCopy0)
						f1f0elemf4.Period = &periodCopy
					}
					if f1f0iter.MetricStat.Stat != nil {
						f1f0elemf4.Stat = f1f0iter.MetricStat.Stat
					}
					if f1f0iter.MetricStat.Unit != nil {
						f1f0elemf4.Unit = svcsdktypes.StandardUnit(*f1f0iter.MetricStat.Unit)
					}
					f1f0elem.MetricStat = f1f0elemf4
				}
				if f1f0iter.Period != nil {
					periodCopy0 := *f1f0iter.Period
					if periodCopy0 > math.MaxInt32 || periodCopy0 < math.MinInt32 {
						return nil, fmt.Errorf("error: field Period is of type int32")
					}
					periodCopy := int32(periodCopy0)
					f1f0elem.Period = &periodCopy
				}
				if f1f0iter.ReturnData != nil {
					f1f0elem.ReturnData = f1f0iter.ReturnData
				}
				f1f0 = append(f1f0, *f1f0elem)
			}
			f1.MetricDataQueries = f1f0
		}
		res.MetricMathAnomalyDetector = f1
	}
	if r.ko.Spec.SingleMetricAnomalyDetector != nil {
		f2 := &svcsdktypes.SingleMetricAnomalyDetector{}
		if r.ko.Spec.SingleMetricAnomalyDetector.AccountID != nil {
			f2.AccountId = r.ko.Spec.SingleMetricAnomalyDetector.AccountID
		}
		if r.ko.Spec.SingleMetricAnomalyDetector.Dimensions != nil {
			f2f1 := []svcsdktypes.Dimension{}
			for _, f2f1iter := range r.ko.Spec.SingleMetricAnomalyDetector.Dimensions {
				f2f1elem := &svcsdktypes.Dimension{}
				if f2f1iter.Name != nil {
					f2f1elem.Name = f2f1iter.Name
				}
				if f2f1iter.Value != nil {
					f2f1elem.Value = f2f1iter.Value
				}
				f2f1 = append(f2f1, *f2f1elem)
			}
			f2.Dimensions = f2f1
		}
		if r.ko.Spec.SingleMetricAnomalyDetector.MetricName != nil {
			f2.MetricName = r.ko.Spec.SingleMetricAnomalyDetector.MetricName
		}
		if r.ko.Spec.SingleMetricAnomalyDetector.Namespace != nil {
			f2.Namespace = r.ko.Spec.SingleMetricAnomalyDetector.Namespace
		}
		if r.ko.Spec.SingleMetricAnomalyDetector.Stat != nil {
			f2.Stat = r.ko.Spec.SingleMetricAnomalyDetector.Stat
		}
		res.SingleMetricAnomalyDetector = f2
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.AnomalyDetector,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "InvalidParameterCombinationException",
		"MissingRequiredParameterException":
		return true
	default:
		return false
	}
}
