// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package insight_rule

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.ApplyOnTransformedLogs, b.ko.Spec.ApplyOnTransformedLogs) {
		delta.Add("Spec.ApplyOnTransformedLogs", a.ko.Spec.ApplyOnTransformedLogs, b.ko.Spec.ApplyOnTransformedLogs)
	} else if a.ko.Spec.ApplyOnTransformedLogs != nil && b.ko.Spec.ApplyOnTransformedLogs != nil {
		if *a.ko.Spec.ApplyOnTransformedLogs != *b.ko.Spec.ApplyOnTransformedLogs {
			delta.Add("Spec.ApplyOnTransformedLogs", a.ko.Spec.ApplyOnTransformedLogs, b.ko.Spec.ApplyOnTransformedLogs)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RuleDefinition, b.ko.Spec.RuleDefinition) {
		delta.Add("Spec.RuleDefinition", a.ko.Spec.RuleDefinition, b.ko.Spec.RuleDefinition)
	} else if a.ko.Spec.RuleDefinition != nil && b.ko.Spec.RuleDefinition != nil {
		if *a.ko.Spec.RuleDefinition != *b.ko.Spec.RuleDefinition {
			delta.Add("Spec.RuleDefinition", a.ko.Spec.RuleDefinition, b.ko.Spec.RuleDefinition)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RuleName, b.ko.Spec.RuleName) {
		delta.Add("Spec.RuleName", a.ko.Spec.RuleName, b.ko.Spec.RuleName)
	} else if a.ko.Spec.RuleName != nil && b.ko.Spec.RuleName != nil {
		if *a.ko.Spec.RuleName != *b.ko.Spec.RuleName {
			delta.Add("Spec.RuleName", a.ko.Spec.RuleName, b.ko.Spec.RuleName)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RuleState, b.ko.Spec.RuleState) {
		delta.Add("Spec.RuleState", a.ko.Spec.RuleState, b.ko.Spec.RuleState)
	} else if a.ko.Spec.RuleState != nil && b.ko.Spec.RuleState != nil {
		if *a.ko.Spec.RuleState != *b.ko.Spec.RuleState {
			delta.Add("Spec.RuleState", a.ko.Spec.RuleState, b.ko.Spec.RuleState)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
