// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AnomalyDetectorSpec defines the desired state of AnomalyDetector.
//
// An anomaly detection model associated with a particular CloudWatch metric,
// statistic, or metric math expression. You can use the model to display a
// band of expected, normal values when the metric is graphed.
//
// If you have enabled unified cross-account observability, and this account
// is a monitoring account, the metric can be in the same account or a source
// account.
type AnomalyDetectorSpec struct {

	// The configuration specifies details about how the anomaly detection model
	// is to be trained, including time ranges to exclude when training and updating
	// the model. You can specify as many as 10 time ranges.
	//
	// The configuration can also include the time zone to use for the metric.
	Configuration *AnomalyDetectorConfiguration `json:"configuration,omitempty"`
	// Use this object to include parameters to provide information about your metric
	// to CloudWatch to help it build more accurate anomaly detection models. Currently,
	// it includes the PeriodicSpikes parameter.
	MetricCharacteristics *MetricCharacteristics `json:"metricCharacteristics,omitempty"`
	// The metric math anomaly detector to be created.
	//
	// When using MetricMathAnomalyDetector, you cannot include the following parameters
	// in the same operation:
	//
	//   - Dimensions
	//
	//   - MetricName
	//
	//   - Namespace
	//
	//   - Stat
	//
	//   - the SingleMetricAnomalyDetector parameters of PutAnomalyDetectorInput
	//
	// Instead, specify the metric math anomaly detector attributes as part of the
	// property MetricMathAnomalyDetector.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	MetricMathAnomalyDetector *MetricMathAnomalyDetector `json:"metricMathAnomalyDetector,omitempty"`
	// A single metric anomaly detector to be created.
	//
	// When using SingleMetricAnomalyDetector, you cannot include the following
	// parameters in the same operation:
	//
	//   - Dimensions
	//
	//   - MetricName
	//
	//   - Namespace
	//
	//   - Stat
	//
	//   - the MetricMathAnomalyDetector parameters of PutAnomalyDetectorInput
	//
	// Instead, specify the single metric anomaly detector attributes as part of
	// the property SingleMetricAnomalyDetector.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	SingleMetricAnomalyDetector *SingleMetricAnomalyDetector `json:"singleMetricAnomalyDetector,omitempty"`
}

// AnomalyDetectorStatus defines the observed state of AnomalyDetector
type AnomalyDetectorStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The unique identifier of the anomaly detector that you created or updated.
	//
	// Regex Pattern: `^[A-Za-z0-9_./:%()+-]+$`
	// +kubebuilder:validation:Optional
	AnomalyDetectorID *string `json:"anomalyDetectorID,omitempty"`
}

// AnomalyDetector is the Schema for the AnomalyDetectors API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type AnomalyDetector struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AnomalyDetectorSpec   `json:"spec,omitempty"`
	Status            AnomalyDetectorStatus `json:"status,omitempty"`
}

// AnomalyDetectorList contains a list of AnomalyDetector
// +kubebuilder:object:root=true
type AnomalyDetectorList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AnomalyDetector `json:"items"`
}

func init() {
	SchemeBuilder.Register(&AnomalyDetector{}, &AnomalyDetectorList{})
}
