// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// InsightRuleSpec defines the desired state of InsightRule.
//
// This structure contains the definition for a Contributor Insights rule. For
// more information about this rule, see Using Constributor Insights to analyze
// high-cardinality data (https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContributorInsights.html)
// in the Amazon CloudWatch User Guide.
type InsightRuleSpec struct {

	// Specify true to have this rule evaluate log events after they have been transformed
	// by Log transformation (https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CloudWatch-Logs-Transformation.html).
	// If you specify true, then the log events in log groups that have transformers
	// will be evaluated by Contributor Insights after being transformed. Log groups
	// that don't have transformers will still have their original log events evaluated
	// by Contributor Insights.
	//
	// The default is false
	//
	// If a log group has a transformer, and transformation fails for some log events,
	// those log events won't be evaluated by Contributor Insights. For information
	// about investigating log transformation failures, see Transformation metrics
	// and errors (https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Transformation-Errors-Metrics.html).
	ApplyOnTransformedLogs *bool `json:"applyOnTransformedLogs,omitempty"`
	// The definition of the rule, as a JSON object. For details on the valid syntax,
	// see Contributor Insights Rule Syntax (https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContributorInsights-RuleSyntax.html).
	//
	// Regex Pattern: `^[\x00-\x7F]+$`
	// +kubebuilder:validation:Required
	RuleDefinition *string `json:"ruleDefinition"`
	// A unique name for the rule.
	//
	// Regex Pattern: `^[\x20-\x7E]+$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	RuleName *string `json:"ruleName"`
	// The state of the rule. Valid values are ENABLED and DISABLED.
	//
	// Regex Pattern: `^[\x20-\x7E]+$`
	RuleState *string `json:"ruleState,omitempty"`
	// A list of key-value pairs to associate with the Contributor Insights rule.
	// You can associate as many as 50 tags with a rule.
	//
	// Tags can help you organize and categorize your resources. You can also use
	// them to scope user permissions, by granting a user permission to access or
	// change only the resources that have certain tag values.
	//
	// To be able to associate tags with a rule, you must have the cloudwatch:TagResource
	// permission in addition to the cloudwatch:PutInsightRule permission.
	//
	// If you are using this operation to update an existing Contributor Insights
	// rule, any tags you specify in this parameter are ignored. To change the tags
	// of an existing rule, use TagResource (https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_TagResource.html).
	Tags []*Tag `json:"tags,omitempty"`
}

// InsightRuleStatus defines the observed state of InsightRule
type InsightRuleStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// An optional built-in rule that Amazon Web Services manages.
	// +kubebuilder:validation:Optional
	ManagedRule *bool `json:"managedRule,omitempty"`
	// For rules that you create, this is always {"Name": "CloudWatchLogRule", "Version":
	// 1}. For managed rules, this is {"Name": "ServiceLogRule", "Version": 1}
	// +kubebuilder:validation:Optional
	Schema *string `json:"schema,omitempty"`
}

// InsightRule is the Schema for the InsightRules API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type InsightRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              InsightRuleSpec   `json:"spec,omitempty"`
	Status            InsightRuleStatus `json:"status,omitempty"`
}

// InsightRuleList contains a list of InsightRule
// +kubebuilder:object:root=true
type InsightRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []InsightRule `json:"items"`
}

func init() {
	SchemeBuilder.Register(&InsightRule{}, &InsightRuleList{})
}
